spring:
  dataSource:
    druid:
      url: jdbc:mysql://10.8.0.1:21306/business_terminal_erp?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 1qazWSX
  cloud:
    sentinel:
      transport:
        dashboard: 10.8.0.1:20501
        port: 20502
      datasource:
        ds:
          nacos:
            server-addr: ${nacos-server-addr}
            namespace: 900930bf-a1c9-4d4b-8b98-fd40d9e05197
            data-id: production-sentinel.json
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
      eager: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

bt:
  snowflake:
    dataId: 1
    workerId: 1

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true